Repository faceshiftlabs/DeepFaceLab, pull requests merged in 2019-12, with the labels that each got.

#100 Feat/flask preview material ui
  flaskr/templates/index.html
Labels: enhancement, ui/ux

#101 Adds `--fp16` argument to train with half-precision floats
  main.py
Labels: deep learning, enhancement

#102 add argument to device_args
  main.py
Labels: deep learning, enhancement

#103 Feat/add fp16 training arg
  main.py
  models/ModelBase.py
Labels: deep learning, enhancement

#66 write current iterations when saving
  models/ModelBase.py
Labels: bug

#83 fixes for paths in various tests
  facelib/test/FacialMesh.py
  facelib/test/LandmarksExtractor.py
  facelib/test/LandmarksProcessor.py
  imagelib/test/color_transfer.py
Labels: bug, test

#82 add optional --output-dir for util
  main.py
  mainscripts/Util.py
Labels: enhancement

#113 Adds option to increase the weight of src loss to dst loss
  models/Model_SAEHD/Model.py
Labels: enhancement

#112 Silence Tensorflow warnings for Tensorflow 1.14.0
  nnlib/nnlib.py
  requirements-cpu.txt
  requirements-cuda.txt
  requirements-opencl.txt
Labels: bug, ui/ux
